true_added=""
breaking_added_props=""

# Read added_extracted and map to raw lines
while IFS= read -r added_line; do
  # Extract property name for matching (e.g., Code from Code:long)
  prop_name=$(echo "$added_line" | cut -d: -f1)

  # Find matching raw added line from added_props
  raw_line=$(echo "$added_props" | grep -E "public.*\b$prop_name\b" | head -n1)

  # Check if it's required
  if echo "$raw_line" | grep -q '\brequired\b'; then
    # If required, check for default assignment
    if echo "$raw_line" | grep -q '='; then
      # Has default → safe
      true_added+="$added_line"$'\n'
    else
      # Required with no default → breaking
      breaking_added_props+="$added_line"$'\n'
    fi
  else
    # Not required → safe
    true_added+="$added_line"$'\n'
  fi
done <<< "$added_extracted"

# Format and print
formatted_added_props=$(echo "$true_added" | sed -E 's/(.*):([^:]+)$/- \1 (\2)/')
added_details+="- $model_name"$'\n'"$formatted_added_props"$'\n'

echo "✅ Added Properties (ONLY):"
echo "$added_details"

if [ -n "$breaking_added_props" ]; then
  echo "⚠️ Breaking Added Properties (Missing Default):"
  echo "$breaking_added_props"
fi