# TYPE-CHANGE
if [ -n "$type_changed" ]; then
  type_formatted_props=$(echo "$type_changed" | sed -E 's/(.*):(.*) -> (.*)/- \1 (\2 → \3)/')

  while IFS= read -r line; do
    original_type=$(echo "$line" | cut -d':' -f2 | cut -d' ' -f1)
    new_type=$(echo "$line" | cut -d'>' -f2 | xargs)

    # Remove trailing `?` to compare base types
    base_old_type=$(echo "$original_type" | sed 's/\?$//')
    base_new_type=$(echo "$new_type" | sed 's/\?$//')

    if [ "$base_old_type" = "$base_new_type" ]; then
      # Only nullable change
      nullable_type_changed+="$line"$'\n'
    else
      # True data type change
      data_type_changed+="$line"$'\n'
    fi
  done <<< "$type_changed"

  if [ -n "$data_type_changed" ]; then
    data_type_changed_output+="- $model_name"$'\n'"$type_formatted_props"$'\n'
  fi

  if [ -n "$nullable_type_changed" ]; then
    nullable_type_changed_output+="- $model_name"$'\n'"$nullable_type_changed"$'\n'
  fi
fi