- name: Get models with only deleted properties
  id: deleted-only-models
  if: ${{ steps.modified-models.outputs.models != '' }}
  run: |
    echo "Checking which modified models only contain deleted properties..."

    deleted_details=""
    deleted_only_models=""

    while read -r file; do
      echo "Processing $file"

      # Get deleted property lines
      deleted_props=$(git diff origin/development -- "$file" \
        | grep '^-' \
        | grep -v '^---' \
        | grep -E 'public\s+[^;{]+{[^}]*}' || true)

      # Get added property lines
      added_props=$(git diff origin/development -- "$file" \
        | grep '^+' \
        | grep -v '^\+\+\+' \
        | grep -v '^+\s*//' \
        | grep -E 'public\s+[^;{]+{[^}]*}' || true)

      if [ -n "$deleted_props" ] && [ -z "$added_props" ]; then
        model_name=$(basename "$file" .cs)
        deleted_only_models+="$model_name;"
        
        # Format deleted properties like "- PropertyName (Type)"
        formatted_props=$(echo "$deleted_props" | sed -E 's/^\-\s*//' \
          | sed -E 's/.*public\s+([^ ]+)\s+([^ ]+).*/- \2 (\1)/')

        deleted_details+="$model_name:\n$formatted_props\n\n"
      fi
    done <<< "${{ steps.modified-models.outputs.models }}"

    # Export outputs
    echo "deleted_only_models=${deleted_only_models}" >> $GITHUB_OUTPUT

    # Export grouped deleted details
    echo "deleted_details<<EOF" >> $GITHUB_OUTPUT
    echo -e "$deleted_details" >> $GITHUB_OUTPUT
    echo "EOF" >> $GITHUB_OUTPUT