- name: Detect breaking changes in modified models
  id: detect-breaking
  run: |
    deleted_list=""
    type_changed_list=""
    required_added_list=""
    
    for file in ${{ steps.all-modified-models.outputs.models }}; do
      model_name=$(basename "$file" .cs)

      old_props=$(git show origin/main:"$file" | grep -E '^\s*public\s+(required\s+)?\w+\s+\w+\s*\{' || true)
      new_props=$(cat "$file" | grep -E '^\s*public\s+(required\s+)?\w+\s+\w+\s*\{' || true)

      # Deleted properties
      deleted=$(comm -23 <(echo "$old_props" | sort) <(echo "$new_props" | sort))
      while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        type=$(echo "$line" | sed -E 's/^\s*public\s+(required\s+)?(\w+)\s+(\w+).*/\2/')
        name=$(echo "$line" | sed -E 's/^\s*public\s+(required\s+)?(\w+)\s+(\w+).*/\3/')
        deleted_list+="$model_name:$name($type);"
      done <<< "$deleted"

      # Required added properties
      required_added=$(echo "$new_props" | grep -E '^\s*public\s+required\s+' || true)
      while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        type=$(echo "$line" | sed -E 's/^\s*public\s+required\s+(\w+)\s+(\w+).*/\1/')
        name=$(echo "$line" | sed -E 's/^\s*public\s+required\s+(\w+)\s+(\w+).*/\2/')
        required_added_list+="$model_name:$name($type);"
      done <<< "$required_added"

      # Type changes
      while IFS= read -r old_line; do
        old_type=$(echo "$old_line" | sed -E 's/^\s*public\s+(required\s+)?(\w+)\s+(\w+).*/\2/')
        old_name=$(echo "$old_line" | sed -E 's/^\s*public\s+(required\s+)?(\w+)\s+(\w+).*/\3/')
        new_line=$(echo "$new_props" | grep -E "\b$old_name\b" || true)
        if [ -n "$new_line" ]; then
          new_type=$(echo "$new_line" | sed -E 's/^\s*public\s+(required\s+)?(\w+)\s+(\w+).*/\2/')
          if [ "$old_type" != "$new_type" ]; then
            type_changed_list+="$model_name:$old_name($old_type → $new_type);"
          fi
        fi
      done <<< "$old_props"
    done

    echo "deleted_properties_list=$deleted_list" >> "$GITHUB_OUTPUT"
    echo "type_changed_properties_list=$type_changed_list" >> "$GITHUB_OUTPUT"
    echo "required_added_properties_list=$required_added_list" >> "$GITHUB_OUTPUT"