# raw_line: Code:string -> string?

# Extract full original and new types
original_type=$(echo "$raw_line" | sed -E 's/^[^:]+:([^ ]+) -> .*/\1/')
new_type=$(echo "$raw_line" | sed -E 's/^.*-> ([^ ]+)/\1/')

# Strip nullable symbol for base type comparison
base_old_type=$(echo "$original_type" | sed 's/\?$//')
base_new_type=$(echo "$new_type" | sed 's/\?$//')

echo "original_type: $original_type"
echo "new_type: $new_type"
echo "base_old_type: $base_old_type"
echo "base_new_type: $base_new_type"